### ISSUE TITLE
Add global styles

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#325]
Please add 
```css
* {
  font-smoothing: subpixel-antialiased;
  box-sizing: border-box;
}
```
