### ISSUE TITLE
[Question] Do we prefer inline media queries or block level media queries?

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#544]
## Inline

```css

h1 {
    font-size: 1rem;

    @media (min-width: 768px) {
          font-size: 1.5rem;
     }
}

```

## Block level

```css

h1 {
    font-size: 1rem;
}

@media (min-width: 768px) {
     h1 {
       font-size: 1.5rem;
     }
}
```
