### ISSUE TITLE
Default HR should be styled

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#710]
Building Snapweb has highlighted that the default `<hr>` is quite ugly when unstyled.

The Snapweb styling is:

```css
hr {
  border: 0;
  height: 0;
  border-top: 1px solid $color-mid-light;
  margin: 2rem 0;
}
```
