### ISSUE TITLE
Update default links, and _patterns_list-link

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#717]
A new link style has been agreed, which @anthonydillon and @nottrobin have separately done some work towards.

### Basic links

After being [implemented by Ant](https://github.com/ubuntudesign/cloud-vanilla-theme/blob/master/scss/modules/_links.scss) in cloud-vanilla-theme, the concept was refined in https://github.com/ubuntudesign/vanilla-design/issues/1, to simplify the base link style down to blue colour, default font-weight, no underline, add underline on hover. As I've implement in [this commit to docs-vanilla-theme](https://github.com/ubuntudesign/docs-vanilla-theme/pull/42/commits/9817e1ce7e2d652b3c7cd77f68ed030b3e26d4e4):

``` scss
a {
  border-bottom: 0;
  color: $link-color;
  font-weight: inherit;

  &:visited {
    color: $link-color;
  }

  &:hover {
    text-decoration: underline;
  }
}

h1 a,
h2 a,
h3 a,
h4 a,
h5 a,
h6 a {
  color: $text-color;
  font-weight: normal;

  &:visited {
    color: $text-color;
  }

  &:hover {
    color: $link-color;
  }
}
```

### Links in navigation

As I understand links in `p-navigation` should follow the same rules as links in headings. Although it was agreed that we should add this to individual navigation patterns rather than adding it to `nav` in general:

``` scss
// patterns_navigation
.p-navigation__link {
  color: $text-color;

  &:hover {
    text-decoration: underline;
    color: $link-color;
  }

  &.is-active {
    font-weight: normal;
  }
}
```

### _patterns_list-link

As discussed in https://github.com/ubuntudesign/vanilla-design/issues/1, there is a need for a list of links, where the links will standout more than regular links. In this case, links should be normal weight (rather than light) and normal text colour, the same as navigation links and headings. However, this should not be the default for links in lists, as we should assume first and foremost that lists contain normal text.

Therefore this should be its own pattern:

``` scss
.p-list-link {
  color: $text-color;

  &:hover {
    text-decoration: underline;
    color: $link-color;
  }
}
```
